language: node_js
node_js:
  - "0.11"
before_install:
  - "curl -0 https://s3.amazonaws.com/bitly-downloads/nsq/nsq-0.2.27.linux-amd64.go1.2.tar.gz | tar -zx"
  - "./nsq-0.2.27.linux-amd64.go1.2/bin/nsqd&"
