// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var co, debug, _;

  debug = require('debug')('trampoline:index');

  _ = require('underscore');

  co = require('co');

  module.exports = co(function*(body) {
    debug('got a request %j', body);
  });

}).call(this);
