// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var co, debug, moment, request, _;

  debug = require('debug')('trampoline:index');

  _ = require('underscore');

  request = require('superagent');

  moment = require('moment');

  co = require('co');

  module.exports = co(function*(data, query) {
    var agent, e, mh, result;
    mh = data['message-headers'];
    if (_.isString(mh)) {
      data['message-headers'] = JSON.parse(mh);
    }
    result = {
      type: query.type || 'unknown',
      time: moment().toISOString(),
      data: data
    };
    debug('got a request %j', result);
    agent = request('post', 'http:/localhost:1080/1.0/event/put');
    try {
      yield agent.send([result]).end.bind(agent);
    } catch (_error) {
      e = _error;
      debug('faild to post to cube with message: %s', e.message);
    }
  });

}).call(this);
